# Generated by Django 3.0.7 on 2020-07-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
